#+title: Adding mesh capabilities to esp32 port
#+author: Eric Gustafson

* Goal
  - [ ] Add route table entries for AP connections

  [2020-09-22 Tue] It looks like it might just work; or just requiring some
  minor adjustments to get the standard freertos lwip routing to work.

* Key areas to learn now to implement this
  [[file:~/esp-idf/components/tcpip_adapter/tcpip_adapter_lwip.c::static%20esp_err_t%20tcpip_adapter_start(tcpip_adapter_if_t%20tcpip_if,%20uint8_t%20*mac,%20tcpip_adapter_ip_info_t%20*ip_info)][tcpip_adapter_start]]


 I am trying to add/rm routes using netif* add/rm, but this is adding
 an network interface, which is wrong.  I might be able to add route
 tables and simply use them in the ip_forward function ...

* lwip router

  There's a #define to get the gateway for a dest on an netif.
  https://www.nongnu.org/lwip/2_0_x/group__lwip__opts__hooks.html

  LWIP_HOOK_ETHARP_GET_GW(if,dest) along with
  LWIP_HOOK_IP4_ROUTE()

  They recommend hiding route tables in the state, but we could also
  place anywhere.
  


  Here's an interesting discussion:
  [[https://lwip-devel.nongnu.narkive.com/w2tydO9u/lwip-as-a-router]]
